CREATE TABLE public.cart_entity (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_entity_id int8 NULL,
	CONSTRAINT cart_entity_pkey PRIMARY KEY (id),
	CONSTRAINT fks6adfxmf0lociswsppyceugaq FOREIGN KEY (user_entity_id) REFERENCES public.user_entity(id)
);