CREATE TABLE public.category_entity (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT category_entity_pkey PRIMARY KEY (id)
);
