DROP TABLE public.order_entity (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_entity_id int8 NULL,
	CONSTRAINT order_entity_pkey PRIMARY KEY (id),
	CONSTRAINT fk6ac04pkrb34qeudvk2g44drrl FOREIGN KEY (user_entity_id) REFERENCES public.user_entity(id)
);
