DROP TABLE public.user_entity (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_joined timestamp NULL,
	email varchar(15) NOT NULL,
	first_name varchar(15) NOT NULL,
	last_name varchar(15) NOT NULL,
	"location" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone_number varchar(13) NOT NULL,
	username varchar(15) NOT NULL,
	cart_entity_id int8 NULL,
	CONSTRAINT user_entity_pkey PRIMARY KEY (id),
	CONSTRAINT fkbdlo9761on9cys246cn1dy9aq FOREIGN KEY (cart_entity_id) REFERENCES public.cart_entity(id)
);